ci: add rust check step (#98)
* ci: add rust check step

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -8,41 +8,40 @@ on:
   pull_request:
   push:
     branches:
-    - main
+      - main
 jobs:
-
   typecheck:
     name: Typecheck specification
     runs-on: ubuntu-22.04
     steps:
-    - name: 📥 Checkout repository
-      uses: actions/checkout@v4
-    - name: 💾 Cache Nix store
-      uses: actions/cache@v3.0.8
-      id: nix-cache
-      with:
-        path: /tmp/nixcache
-        key: ${{ runner.os }}-nix-typecheck-${{ hashFiles('flake.lock') }}
-        restore-keys: ${{ runner.os }}-nix-typecheck-
-    - name: 🛠️ Install Nix
-      uses: cachix/install-nix-action@v21
-      with:
-        nix_path: nixpkgs=channel:nixos-unstable
-        install_url: https://releases.nixos.org/nix/nix-2.10.3/install
-        extra_nix_config: |
-          allowed-uris = ${{ env.ALLOWED_URIS }}
-          trusted-public-keys = ${{ env.TRUSTED_PUBLIC_KEYS }}
-          substituters = ${{ env.SUBSTITUTERS }}
-          experimental-features = nix-command flakes
-    - name: 💾➤ Import Nix store cache
-      if: "steps.nix-cache.outputs.cache-hit == 'true'"
-      run: "nix-store --import < /tmp/nixcache"
-    - name: 🏗️ Build specification
-      run: |
-        nix build --show-trace --accept-flake-config .#leiosSpec
-    - name: ➤💾 Export Nix store cache
-      if: "steps.nix-cache.outputs.cache-hit != 'true'"
-      run: "nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache"
+      - name: 📥 Checkout repository
+        uses: actions/checkout@v4
+      - name: 💾 Cache Nix store
+        uses: actions/cache@v3.0.8
+        id: nix-cache
+        with:
+          path: /tmp/nixcache
+          key: ${{ runner.os }}-nix-typecheck-${{ hashFiles('flake.lock') }}
+          restore-keys: ${{ runner.os }}-nix-typecheck-
+      - name: 🛠️ Install Nix
+        uses: cachix/install-nix-action@v21
+        with:
+          nix_path: nixpkgs=channel:nixos-unstable
+          install_url: https://releases.nixos.org/nix/nix-2.10.3/install
+          extra_nix_config: |
+            allowed-uris = ${{ env.ALLOWED_URIS }}
+            trusted-public-keys = ${{ env.TRUSTED_PUBLIC_KEYS }}
+            substituters = ${{ env.SUBSTITUTERS }}
+            experimental-features = nix-command flakes
+      - name: 💾➤ Import Nix store cache
+        if: "steps.nix-cache.outputs.cache-hit == 'true'"
+        run: "nix-store --import < /tmp/nixcache"
+      - name: 🏗️ Build specification
+        run: |
+          nix build --show-trace --accept-flake-config .#leiosSpec
+      - name: ➤💾 Export Nix store cache
+        if: "steps.nix-cache.outputs.cache-hit != 'true'"
+        run: "nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') > /tmp/nixcache"
 
   compile:
     name: Build Haskell packages with GHC ${{ matrix.ghc-version }} on ${{ matrix.os }}
@@ -51,7 +50,7 @@ jobs:
       fail-fast: false
       matrix:
         os: [ubuntu-22.04]
-        ghc-version: ['9.8']
+        ghc-version: ["9.8"]
 
     steps:
       - uses: actions/checkout@v4
@@ -62,7 +61,7 @@ jobs:
         with:
           ghc-version: ${{ matrix.ghc-version }}
           # Defaults, added for clarity:
-          cabal-version: 'latest'
+          cabal-version: "latest"
           cabal-update: true
       - name: Install libraries
         run: sudo apt-get install -y libpango1.0-dev libgtk-3-dev
@@ -102,6 +101,20 @@ jobs:
       - name: Run tests
         run: cabal test all
 
+  rs-compile:
+    name: Check Rust packages
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check Rust packages compilation
+        working-directory: sim-rs
+        run: |
+          cargo check
+          if [ $? -ne 0 ]; then
+            echo "Cargo check failed"
+            exit 1
+          fi
+
   fourmolu-check:
     name: Check Haskell sources with fourmolu
     runs-on: ubuntu-22.04
@@ -122,7 +135,7 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 20
-          cache: 'yarn'
+          cache: "yarn"
           cache-dependency-path: site/yarn.lock
 
       - name: 📦 Install dependencies
