Added benchmarks to CI

diff --git a/.github/workflows/crypto-benchmarks-rs.yaml b/.github/workflows/crypto-benchmarks-rs.yaml
--- a/.github/workflows/crypto-benchmarks-rs.yaml
+++ b/.github/workflows/crypto-benchmarks-rs.yaml
@@ -11,7 +11,8 @@ on:
       - "crypto-benchmarks.rs/**"
 
 jobs:
-  crypto-benchmarks-rs-check:
+
+  crypto-benchmarks-rs-test:
     name: "Test"
     runs-on: ubuntu-22.04
     steps:
@@ -22,5 +23,19 @@ jobs:
           cargo test
           if [ $? -ne 0 ]; then
             echo "Cargo test failed"
+            exit 1
+          fi
+
+  crypto-benchmarks-rs-benchmark:
+    name: "Benchmark"
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v4
+      - name: Test Rust packages
+        working-directory: crypto-benchmarks.rs
+        run: |
+          cargo bench
+          if [ $? -ne 0 ]; then
+            echo "Cargo benchmarks failed"
             exit 1
           fi
